import React from "react";

const Tos = () => {
  return (
    <main className={'container mx-auto w-1/2 space-y-5 pb-10 pt-10 bg-gray-100 p-20 overflow-visible'}>
        <div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'center'}}><strong><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>TERMS OF SERVICE</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'center'}}><strong><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Last updated:&nbsp;28/03/2022</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'decimal', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Introduction</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Welcome to&nbsp;</span><strong><span style={{fontFamily: '"Arial",sans-serif'}}>PearEasy ApS</span></strong><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;(“<strong>Company</strong>”, “<strong>we</strong>”, “<strong>our</strong>”, “<strong>us</strong>”)<span style={{color: 'black'}}>! As you have just clicked our Terms of Service, please pause, grab a cup of coffee and carefully read the following pages. It will take you approximately 20&nbsp;minutes.</span></span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>These Terms of Service (“<strong>Terms</strong>”, “<strong>Terms of Service</strong>”) govern your use of&nbsp;our web pages located at easysbc.io</span><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;operated by PearEasy ApS.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Our Privacy Policy also governs your use of our Service and explains how we collect, safeguard and disclose information that results from your use of our web pages. Please read it here easysbc.io/privacy.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Your agreement with us includes these Terms&nbsp;and our Privacy Policy&nbsp;(“<strong>Agreements</strong>”). You acknowledge that you have read and understood Agreements by accessing or using any part of our Services, and agree to be bound of them.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>If you do not agree with (or cannot comply with) Agreements, then you may not use the Service, but please let us know by emailing at peareasy.sbc@gmail.com so we can try to find a solution. These Terms apply to all visitors, users and others who wish to access or use Service.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Thank you for being responsible.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Content</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Content found on or through this Service are the property of&nbsp;PearEasy ApS&nbsp;or used with permission. You may not distribute, modify, transmit, reuse, download, repost, copy, or use said Content, whether in whole or in part, for commercial purposes or for personal gain, without express advance written permission from us.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Prohibited Uses</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>You may use Service only for lawful purposes and in accordance with Terms. You agree not to use Service:</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>In any way that violates any applicable national or international law or regulation.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content or otherwise.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>To transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter,” “spam,” or any other similar solicitation.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>To impersonate or attempt to impersonate Company, a Company employee, another user, or any other person or entity.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>In any way that infringes upon the rights of others, or in any way is illegal, threatening, fraudulent, or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of Service, or which, as determined by us, may harm or offend Company or users of Service or expose them to liability.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Additionally, you agree not to:</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Use Service in any manner that could disable, overburden, damage, or impair Service or interfere with any other party’s use of Service, including their ability to engage in real time activities through Service.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Use any robot, spider, or other automatic device, process, or means to access Service for any purpose, including monitoring or copying any of the material on Service.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Use any manual process to monitor or copy any of the material on Service or for any other unauthorized purpose without our prior written consent.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Use any device, software, or routine that interferes with the proper working of Service.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of Service, the server on which Service is stored, or any server, computer, or database connected to Service.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Attack Service via a denial-of-service attack or a distributed denial-of-service attack.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Take any action that may damage or falsify Company rating.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '35.7pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Otherwise attempt to interfere with the proper working of Service.</span></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Analytics</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><strong><u><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></u></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>We may use third-party Service Providers to monitor and analyze the use of our Service.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><strong><span style={{fontFamily: '"Arial",sans-serif'}}>Google Analytics</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:&nbsp;</span><a href="https://policies.google.com/privacy?hl=en"><span style={{fontFamily: '"Arial",sans-serif'}}>https://policies.google.com/privacy?hl=en</span></a></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><u><span style={{fontFamily: '"Arial",sans-serif', color: 'blue'}}>&nbsp;</span></u></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>We also encourage you to review the Google's policy for safeguarding your data:&nbsp;</span><a href="https://support.google.com/analytics/answer/6004245"><span style={{fontFamily: '"Arial",sans-serif'}}>https://support.google.com/analytics/answer/6004245</span></a><span style={{fontFamily: '"Arial",sans-serif'}}>.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>No Use By Minors</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Service is intended only for access and use by individuals at least eighteen (18) years old. By accessing or using any of Company, you warrant and represent that you are at least eighteen (18) years of age and with the full authority, right, and capacity to enter into this agreement and abide by all of the terms and conditions of Terms. If you are not at least eighteen (18) years old, you are prohibited from both the access and usage of Service.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Accounts</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>When you create an account with us, you guarantee that you are above the age of 18, and that the information you provide us is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on Service.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>You are responsible for maintaining the confidentiality of your account and password, including but not limited to the restriction of access to your computer and/or account. You agree to accept responsibility for any and all activities or actions that occur under your account and/or password, whether your password is with our Service or a third-party service. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you, without appropriate authorization. You may not use as a username any name that is offensive, vulgar or obscene.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>We reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in our sole discretion.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Intellectual Property</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>This Agreement does not transfer from Company to you any Company or third party intellectual property, and all right, title, and interest in and to such property will remain (as between the parties) solely with Company. Company, Service, the Company logo and the Service logo, and all other trademarks, service marks, graphics and logos used in connection with easysbc.io or our Services, are trademarks or registered trademarks of Company or Company’s licensors. Other trademarks, service marks, graphics and logos used in connection with our Services may be the trademarks of other third parties. Your use of our Services grants you no right or license to reproduce or otherwise use any Company or third-party trademarks.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Error Reporting and Feedback</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>You may provide us&nbsp;either directly at peareasy.sbc@gmail.com or via third party sites and tools&nbsp;with information and feedback concerning errors, suggestions for improvements, ideas, problems, complaints, and other matters related to our Service (“<strong>Feedback</strong>”). You acknowledge and agree that: (i) you shall not retain, acquire or assert any intellectual property right or other right, title or interest in or to the Feedback; (ii) Company may have development ideas similar to the Feedback; (iii) Feedback does not contain confidential information or proprietary information from you or any third party; and (iv) Company is not under any obligation of confidentiality with respect to the Feedback. In the event the transfer of the ownership to the Feedback is not possible due to applicable mandatory laws, you grant Company and its affiliates an exclusive, transferable, irrevocable, free-of-charge, sub-licensable, unlimited and perpetual right to use (including copy, modify, create derivative works, publish, distribute and commercialize) Feedback in any manner and for any purpose.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>The third party sites and tools mentioned above include the following:</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><strong><span style={{fontFamily: '"Arial",sans-serif'}}>Bugsnag</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>Bugsnag is a platform for monitoring and logging stability of applications provided by Bugsnag Inc. Please read their Privacy Policy here: https://docs.bugsnag.com/legal/privacy-policy/&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><strong><span style={{fontFamily: '"Arial",sans-serif'}}>ACRA</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>ACRA or Application Crash Reports for Android is monitoring platform. Please find more information here:&nbsp;</span><a href="https://github.com/ACRA/acra"><span style={{fontFamily: '"Arial",sans-serif'}}>https://github.com/ACRA/acra</span></a><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><strong><span style={{fontFamily: '"Arial",sans-serif'}}>Rollbar</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Rollbar is error tracking service provided by Rollbar Inc. Find out more here:&nbsp;</span><a href="https://docs.rollbar.com/docs/privacy-policy"><span style={{fontFamily: '"Arial",sans-serif'}}>https://docs.rollbar.com/docs/privacy-policy</span></a><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><strong><span style={{fontFamily: '"Arial",sans-serif'}}>Sentry</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Sentry is open-source error tracking solution provided by Functional Software Inc. More information is available here:&nbsp;</span><a href="https://sentry.io/privacy/"><span style={{fontFamily: '"Arial",sans-serif'}}>https://sentry.io/privacy/</span></a><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><strong><span style={{fontFamily: '"Arial",sans-serif'}}>Raygun</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Raygun is automated error monitoring software provided by Raygun Limited. Privacy Policy is accessible at&nbsp;</span><a href="https://raygun.com/privacy/"><span style={{fontFamily: '"Arial",sans-serif'}}>https://raygun.com/privacy/</span></a><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><strong><span style={{fontFamily: '"Arial",sans-serif'}}>Firebase Crashlytics</span></strong></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Firebase Crashlytics is&nbsp;</span><span style={{fontFamily: '"Arial",sans-serif'}}>bug reporting service provided by Google Inc.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy?hl=en</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{color: 'blue', textDecoration: 'underline'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>For more information on what type of information Firebase collects, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{color: 'blue', textDecoration: 'underline'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Links To Other Web Sites</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Our Service may contain links to third party web sites or services that are not owned or controlled by&nbsp;PearEasy ApS.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif'}}>PearEasy ApS&nbsp;has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>YOU ACKNOWLEDGE AND AGREE THAT&nbsp;</span><span style={{fontFamily: '"Arial",sans-serif'}}>PearEasy ApS</span><span style={{fontFamily: '"Arial",sans-serif'}}>&nbsp;<span style={{color: 'black'}}>SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH CONTENT, GOODS OR SERVICES AVAILABLE ON OR THROUGH ANY SUCH THIRD PARTY WEB SITES OR SERVICES.</span></span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>WE STRONGLY ADVISE YOU TO READ THE TERMS OF SERVICE AND PRIVACY POLICIES OF ANY THIRD PARTY WEB SITES OR SERVICES THAT YOU VISIT.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Disclaimer Of Warranty&nbsp;</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>THESE SERVICES ARE PROVIDED BY COMPANY ON AN “AS IS” AND “AS AVAILABLE” BASIS. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THEIR SERVICES, OR THE INFORMATION, CONTENT OR MATERIALS INCLUDED THEREIN. YOU EXPRESSLY AGREE THAT YOUR USE OF THESE SERVICES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED FROM US IS AT YOUR SOLE RISK.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>NEITHER COMPANY NOR ANY PERSON ASSOCIATED WITH COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER COMPANY NOR ANYONE ASSOCIATED WITH COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, THEIR CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE SERVICES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Limitation Of Liability</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>EXCEPT AS PROHIBITED BY LAW, YOU WILL HOLD US AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES (INCLUDING ATTORNEYS' FEES AND ALL RELATED COSTS AND EXPENSES OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTED), WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM THIS AGREEMENT AND ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF COMPANY HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS LIABILITY FOUND ON THE PART OF COMPANY, IT WILL BE LIMITED TO THE AMOUNT PAID FOR THE PRODUCTS AND/OR SERVICES, AND UNDER NO CIRCUMSTANCES WILL THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Indemnification</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>You agree to indemnify and hold harmless Company, its contractors, and its licensors, and their respective directors, officers, employees, and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of our Services, including but not limited to your violation of this Agreement.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Termination</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>We may terminate or suspend your account and bar access to Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of Terms.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>If you wish to terminate your account, you may simply discontinue using Service.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>All provisions of Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Governing Law</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>These Terms shall be governed and construed in accordance with the laws of Denmark, excluding its conflict of law provisions, and the venue for any disputes arising out of or relating to any of the same will be Denmark.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service and supersede and replace any prior agreements we might have had between us regarding Service.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Changes To Service</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>We reserve the right to withdraw or amend our Service, and any service or material we provide via Service, in our sole discretion without notice. We will not be liable if for any reason all or any part of Service is unavailable at any time or for any period. From time to time, we may restrict access to some parts of Service, or the entire Service, to users, including registered users.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Amendments To Terms</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>We may amend Terms at any time by posting the amended terms on this site. It is your responsibility to review these Terms periodically.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Your continued use of the Platform following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently so you are aware of any changes, as they are binding on you.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Service.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Waiver And Severability</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>No waiver by Company of any term or condition set forth in Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Company to assert a right or provision under Terms shall not constitute a waiver of such right or provision.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>If any provision of Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of Terms will continue in full force and effect.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify', background: 'white'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Acknowledgement</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>BY USING SERVICE OR OTHER SERVICES PROVIDED BY US, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>&nbsp;</span></p>
            <div style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}>
                <ol style={{marginBottom: '0cm', listStyleType: 'undefined', marginLeft: '7.850000000000001px'}}>
                    <li style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Cambria",serif'}}><strong><u><span style={{}}>Contact Us</span></u></strong></li>
                </ol>
            </div>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>Please send your feedback, comments, requests for technical support:</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>By email: peareasy.sbc@gmail.com.</span></p>
            <p style={{marginTop: '0cm', marginRight: '0cm', marginBottom: '0cm', marginLeft: '17.85pt', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Cambria",serif', textAlign: 'justify'}}><span style={{fontFamily: '"Arial",sans-serif', color: 'black'}}>By visiting this page on our website: easysbc.io/contact.</span></p>
        </div>
    </main>
  )
}

export default Tos
